FROM quay.io/jupyter/all-spark-notebook:2025-12-10

ARG JUPYTER_CONFIG_FILE="/home/${NB_USER}/.jupyter/jupyter_server_config.py"

RUN mamba install --yes 'pyspark=4.0.1' && \
    pip install 'delta-spark==4.0.0' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER root

RUN tee -a "${SPARK_HOME}/conf/spark-defaults.conf" <<EOF
# Delta Lake Spark Extensions
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
EOF

RUN mkdir -p /home/${NB_USER}/.jupyter

RUN tee -a "${JUPYTER_CONFIG_FILE}" <<EOF
# Jupyter Server Configuration
c.ServerApp.root_dir = '/home/${NB_USER}/work'
c.ServerApp.token = '${JSPARK_TOKEN}'
c.ServerApp.allow_remote_access = True
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.allow_root = True
c.ServerApp.base_url = '/jupyterlab'
EOF

COPY --chown=${NB_USER}:${NB_UID} ./ipython-startup /home/${NB_USER}/.ipython/profile_default/startup

RUN fix-permissions "/home/${NB_USER}/.ipython"

USER ${NB_USER}

