FROM quay.io/jupyter/all-spark-notebook:2024-10-20


RUN mamba install --yes 'delta-spark' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER root

RUN echo 'spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension' >> "${SPARK_HOME}/conf/spark-defaults.conf" && \
    echo 'spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog' >> "${SPARK_HOME}/conf/spark-defaults.conf"  && \
    echo "c.ServerApp.root_dir = '/home/${NB_USER}/work'"  >> /home/${NB_USER}/.jupyter/jupyter_server_config.py && \
    echo "c.ServerApp.token = '${JSPARK_TOKEN}'"  >> /home/${NB_USER}/.jupyter/jupyter_server_config.py && \
    echo "c.ServerApp.allow_remote_access = True" >> /home/${NB_USER}/.jupyter/jupyter_server_config.py && \
    echo "c.ServerApp.ip = '*'" >> /home/${NB_USER}/.jupyter/jupyter_server_config.py && \
    echo "c.ServerApp.allot_root = True" >> /home/${NB_USER}/.jupyter/jupyter_server_config.py && \
    echo "c.ServerApp.base_url = '/jupyterlab'" >> /home/${NB_USER}/.jupyter/jupyter_server_config.py

COPY --chown=${NB_USER}:${NB_UID} ./ipython-startup /home/${NB_USER}/.ipython/profile_default/startup 

RUN chown -R ${NB_USER}:${NB_UID} /home/${NB_USER}/.ipython

USER ${NB_UID}

# Trigger download of delta lake files
RUN echo "from pyspark.sql import SparkSession" > /tmp/init-delta.py && \
    echo "from delta import *" >> /tmp/init-delta.py && \
    echo "spark = configure_spark_with_delta_pip(SparkSession.builder).getOrCreate()" >> /tmp/init-delta.py && \
    python /tmp/init-delta.py && \
    rm /tmp/init-delta.py