name: Audit compose file

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Audit compose file
      run: docker compose config --quiet && printf "OK\n" || printf "AUDIT FAILED!\n"%% exit 1
